---
    - name: Pip3 Module Install
      hosts: localhost
      gather_facts: false
      tasks:
      - name: Install Pip Modules
        pip:
          name: "{{ item }}"
          executable: pip3
        with_items:
          - wheel
          - setuptools
          - pywinrm
          - pyvmomi
          - requests-credssp
          - paramiko
          - simplejson